修复Linux版本严重错误，细节微调，更正大量语法错误，添加中文README。
FastGitORG/fgit pull request #1
Opened 2020-08-13 13:01 UTC by Mivik

RT

~~（话说你有在 Linux 上测试吗... 你原来的版本多加了一个/根本不能用来着（（~~

2020-08-13 13:16 UTC, xkeyC commented
坚持 bin 原则，另外不建议使用复制，后期更新可通过 git pull获取

2020-08-13 16:49 UTC, KevinZonda requested changes

2020-08-13 16:49 UTC, KevinZonda commented on scripts/fgit.sh
> +echo "Error: $1 is not a GitHub URL!"
indentation

2020-08-13 16:49 UTC, KevinZonda commented on README-zh_CN.md
> +## 如何使用？
MD022/blanks-around-headings/blanks-around-headers: Headings should be surrounded by blank lines 
See more [here](https://github.com/updownpress/markdown-lint/blob/master/rules/022-blanks-around-headers.md).

2020-08-13 16:49 UTC, KevinZonda commented on README.md
> +## How To Use?
MD022/blanks-around-headings/blanks-around-headers: Headings should be surrounded by blank lines 
See more [here](https://github.com/updownpress/markdown-lint/blob/master/rules/022-blanks-around-headers.md).

2020-08-13 16:49 UTC, KevinZonda commented on README.md
>  ### Linux
Maybe adding Unix is better?

2020-08-13 16:49 UTC, KevinZonda commented on README.md
> -2. eq: `sudo ln -s /home/username/tools/fgit/bin/fgit.sh /bin/fgit`
Using `~` to replace `/home/username/`

2020-08-13 16:49 UTC, KevinZonda commented on README.md
> +3. Use command `fgit https://github.com/xxx/xxx.git` to  use fastgit.org to clone the repository
Two spaces inserted before `use fastgit,org` should be removed.

2020-08-13 16:49 UTC, KevinZonda commented on scripts/fgit.sh
> +# author: xkeyC
Add your name

2020-08-13 16:49 UTC, KevinZonda commented on scripts/fgit.sh
> +# url: github.com/xkeyC
Add your github url

2020-08-13 16:56 UTC, KevinZonda requested changes

2020-08-13 16:56 UTC, KevinZonda commented on scripts/fgit.sh
> +if [ "$1" == "" ];then
Uniform code style. Use 
```bash
if [ ]; then
fi
```

or 

```bash
if [ ]
then
fi
```

2020-08-14 00:08 UTC, Mivik commented on README.md
> -2. eq: `sudo ln -s /home/username/tools/fgit/bin/fgit.sh /bin/fgit`
it's removed

2020-08-14 00:09 UTC, Mivik commented on scripts/fgit.sh
> +if [ "$1" == "" ];then
note that i didn't modify the style.

2020-08-14 01:00 UTC, KevinZonda approved these changes

2020-09-01 01:21 UTC, merged